version: "3"
services:
  orskbot:
    build: .
    image: orskbot:200421
    container_name: orskbot
    restart: always
    network_mode: "host"
    volumes:
     - ./config.py:/opt/orskbot/config.py
